cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
    - node_modules/

build:
  image: node:lts-alpine
  stage: build
  artifacts:
    expire_in: 2 days
    paths:
      - ./
  only:
    - release
  script:
    - apk add python
    - yarn install --progress=false
    - yarn build

deploy:
  image: alpine
  stage: deploy
  artifacts:
    expire_in: 2 days
    paths:
      - ./
  only:
    - release
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete ./ $SSH_USER@$SERVER:/var/www/$SSH_USER/www/frontend_deploy_tmp
    - ssh -T $SSH_USER@$SERVER 'cp -rf ~/www/frontend_deploy_tmp/* ~/www/frontend && rm -rf ~/www/frontend_deploy_tmp'
